### ISSUE TITLE
Cooking Pot Recipe

### ISSUE THREAD

**Issue by StrayWolfe** [StrayWolfe/Cooking-with-TFC#1]
Cooking Pot recipes are acting as shaped recipes instead of shapeless recipes in v0.0.4.1. Maybe there is something going wrong with an unsupported java or forge version?

**Comment by Monarch-of-Gold** [comment]
Currently running Java 8 Update 91 and Forge 10.13.4.1614 (the latest version for 1.7.10) with LiteLoader (for VoxelMap). As far as I'm aware, those should be supported. I'll try another soup sometime when I have the ingredients to and let you know if I have the same problem. Either that or I'll get a creative world going to see what's going on.

Sorry about this!

**Comment by Monarch-of-Gold** [comment]
Okay, so I did some testing, and, yes, the recipes are shapeless. I must've been getting something wrong without realizing it. Sorry again for the confusion!

**Comment by StrayWolfe** [comment]
Thanks for the report and testing.
