### ISSUE TITLE
[SOLVED] Making salads without having to cut stuff

### ISSUE THREAD

**Issue by AkashaP** [StrayWolfe/Cooking-with-TFC#17]
It's pretty annoying having to fill up my entire inventory with split stacks to get an ingredient under 2 ounces so that it fits in the salad bowl especially with a large stack. It just feels easier to eat the ingredients directly. Why not just take 2 ounces directly from the ingredient stack?

**Comment by UnlimatedStone9** [comment]
It already does this...

**Comment by AkashaP** [comment]
Last time I tried it didn't do that without having to cut it down to a small size first

**Comment by AkashaP** [comment]
@UnlimatedStone9 is right, it does already do this. I did not realise the knife had to be actually **ON THE HOTBAR** in order for it to work. The wiki did not mention this however, just that you had to have a knife.
