### ISSUE TITLE
Broth Decay and Clay Oven

### ISSUE THREAD

**Issue by SkyLord3000** [StrayWolfe/Cooking-with-TFC#2]
The broth decay rate is insane, ~.5% a second! Please fix this as it is unusable at this rate, and the clay oven will not harden regardless of time and if it's sheltered from rain.

**Comment by StrayWolfe** [comment]
I've been unable to get the broth to decay any more than normal. I will keep an eye on it and see if there is any way for me to cause it to rapidly decay. I suspect you have gotten to the point with the oven that requires burning fuel in it to harden. Unless you burn something in it, it will never harden. Thank you for the report.
