### ISSUE TITLE
Description: Ticking block entity

### ISSUE THREAD

**Issue by 0999312langball** [StrayWolfe/Cooking-with-TFC#4]
crash-report
---- Minecraft Crash Report ---- // Ooh. Shiny. Time: 16-12-5 ä¸Šåˆ5:40 Description: Ticking block entity java.lang.NoSuchMethodError: com.bioxx.tfc.Core.TFC_Core.isExposedToRain(Lnet/minecraft/world/World;III)Z at straywolfe.cookingwithtfc.common.tileentity.TileClayOven.func_145845_h(TileClayOven.java:101) at net.minecraft.world.World.func_72939_s(World.java:1939) at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) A detailed walkthrough of the error, its code path and all known details is as follows: --------------------------------------------------------------------------------------- -- Head -- Stacktrace: at straywolfe.cookingwithtfc.common.tileentity.TileClayOven.func_145845_h(TileClayOven.java:101) at net.minecraft.world.World.func_72939_s(World.java:1939) -- Block entity being ticked -- Details: Name: TileClayOven // straywolfe.cookingwithtfc.common.tileentity.TileClayOven Block type: ID #669 (tile.ClayOven // straywolfe.cookingwithtfc.common.block.BlockClayOven) Block data value: 1 / 0x1 / 0b0001 Block location: World: (5965,136,-12281), Chunk: (at 13,8,7 in 372,-768; contains blocks 5952,0,-12288 to 5967,255,-12273), Region: (11,-24; contains chunks 352,-768 to 383,-737, blocks 5632,0,-12288 to 6143,255,-11777) Actual block type: ID #669 (tile.ClayOven // straywolfe.cookingwithtfc.common.block.BlockClayOven) Actual block data value: 1 / 0x1 / 0b0001 Stacktrace: at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) -- Affected level -- Details: Level name: 0999312 All players: 1 total; [EntityPlayerMP['Kijin Seija'/187, l='0999312', x=5966.30, y=138.00, z=-12280.03]] Chunk stats: ServerChunkCache: 360 Drop: 0 Level seed: -86754689866765 Level generator: ID 00 - TFCDefault, ver 0. Features enabled: true Level generator options: Level spawn location: World: (5908,147,-12224), Chunk: (at 4,9,0 in 369,-764; contains blocks 5904,0,-12224 to 5919,255,-12209), Region: (11,-24; contains chunks 352,-768 to 383,-737, blocks 5632,0,-12288 to 6143,255,-11777) Level time: 619600 game time, 619600 day time Level dimension: 0 Level storage version: 0x04ABD - Anvil Level weather: Rain time: 18996 (now: false), thunder time: 62227 (now: false) Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false Stacktrace: at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) -- System Details -- Details: Minecraft Version: 1.7.10 Operating System: Windows XP (x86) version 5.1 Java Version: 1.7.0_80, Oracle Corporation Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation Memory: 106320120 bytes (101 MB) / 606773248 bytes (578 MB) up to 1037959168 bytes (989 MB) Mod Pack: Unknown / None LiteLoader Mods: none LaunchWrapper: 40 active transformer(s) - Transformer: cpw.mods.fml.common.asm.transformers.PatchingTransformer - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer - Transformer: cpw.mods.fml.common.asm.transformers.MarkerTransformer - Transformer: cpw.mods.fml.common.asm.transformers.SideTransformer - Transformer: cpw.mods.fml.common.asm.transformers.EventSubscriptionTransformer - Transformer: net.minecraftforge.classloading.FluidIdTransformer - Transformer: com.bioxx.tfc.ASM.Transform.TF_EntityRenderer - Transformer: com.bioxx.tfc.ASM.Transform.TF_RenderGlobal - Transformer: com.bioxx.tfc.ASM.Transform.TF_EntityLeashKnot - Transformer: com.bioxx.tfc.ASM.Transform.TF_EntityPlayerMP - Transformer: com.bioxx.tfc.ASM.Transform.TF_EntityPlayer - Transformer: com.peffern.pumpkins.asm.BlockSetupCT - Transformer: com.peffern.pumpkins.asm.BlockRenderHandlerCT - Transformer: com.peffern.pumpkins.asm.ContainerPlayerTFC_CT - Transformer: com.peffern.pumpkins.asm.BiomeDecoratorTFC_CT - Transformer: codechicken.lib.asm.ClassHeirachyManager - Transformer: codechicken.core.asm.InterfaceDependancyTransformer - Transformer: codechicken.core.asm.TweakTransformer - Transformer: codechicken.core.asm.DelegatedTransformer - Transformer: codechicken.core.asm.DefaultImplementationTransformer - Transformer: codechicken.nei.asm.NEITransformer - Transformer: com.vidaj.tfcrailcraft.asm.AsmManager - Transformer: me.guichaguri.betterfps.transformers.MathTransformer - Transformer: me.guichaguri.betterfps.transformers.EventTransformer - Transformer: cpw.mods.fml.common.asm.transformers.DeobfuscationTransformer - Transformer: cpw.mods.fml.common.asm.transformers.AccessTransformer - Transformer: net.minecraftforge.transformers.ForgeAccessTransformer - Transformer: codechicken.core.asm.CodeChickenAccessTransformer - Transformer: cpw.mods.fml.common.asm.transformers.ModAccessTransformer - Transformer: cpw.mods.fml.common.asm.transformers.ItemStackTransformer - Transformer: farseek.core.FarseekClassTransformer - Transformer: streams.core.StreamsClassTransformer - Transformer: fastcraft.J - Transformer: cpw.mods.fml.common.asm.transformers.TerminalTransformer - Transformer: com.mumfrey.liteloader.client.transformers.LiteLoaderEventInjectionTransformer - Transformer: com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer - Transformer: com.mumfrey.liteloader.client.transformers.MinecraftOverlayTransformer - Transformer: cpw.mods.fml.common.asm.transformers.ModAPITransformer JVM Flags: 1 total; -Xmx1024m AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0 FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 33 mods loaded, 33 mods active States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) UCHIJAAAA	tfc_coremod{0.79.28} [TFC[coremod]] (minecraft.jar) UCHIJAAAA CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) UCHIJAAAA	NotEnoughItems{1.0.3.74} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.3.74-universal.jar) UCHIJAAAA	FastCraft{1.23} [FastCraft] (fastcraft-1.23.jar) UCHIJAAAA dynamicswordskills{1.7.10-v1.5.1} [Dynamic Sword Skills] (%5B1.7.10%5DCore-dynamicswordskills-v1.5.1.jar) UCHIJAAAA terrafirmacraft{0.79.28} [TerraFirmaCraft] (%5B1.7.10%5DTerraFirmaCraft-0.79.28.908.jar) UCHIJAAAA	lwstfc{3.9.B79} [Leather Water Sac] ([1.7.10]LeatherWaterSac-3.9.B79.jar) UCHIJAAAA	TerraFirmaPumpkins{1.3} [TerraFirmaPumpkins] ([1.7.10]TerraFirmaPumpkins-1.3.jar) UCHIJAAAA	tfcm{0.13.0} [TerraMisc] ([1.7.10]TerraMisc-0.13.0.jar) UCHIJAAAA BiblioCraft{1.11.5} [BiblioCraft] (BiblioCraft[v1.11.5][MC1.7.10].jar) UCHIJAAAA	BuildCraft|Core{7.1.14} [BuildCraft] (buildcraft-7.1.14.jar) UCHIJAAAA	BuildCraft|Builders{7.1.14} [BC Builders] (buildcraft-7.1.14.jar) UCHIJAAAA	BuildCraft|Transport{7.1.14} [BC Transport] (buildcraft-7.1.14.jar) UCHIJAAAA	BuildCraft|Energy{7.1.14} [BC Energy] (buildcraft-7.1.14.jar) UCHIJAAAA BuildCraft|Silicon{7.1.14} [BC Silicon] (buildcraft-7.1.14.jar) UCHIJAAAA	BuildCraft|Robotics{7.1.14} [BC Robotics] (buildcraft-7.1.14.jar) UCHIJAAAA	BuildCraft|Factory{7.1.14} [BC Factory] (buildcraft-7.1.14.jar) UCHIJAAAA	Railcraft{9.12.2.0} [Railcraft] (Railcraft_1.7.10-9.12.2.0.jar) UCHIJAAAA	tfctech{0.2.9-A14} [Shurgent's TFCTech Addon] ([1.7.10]TFCTech-0.2.9-A14.jar) UCHIJAAAA	WIT{1.0.8} [WIT] ([æˆ‘çœ‹åˆ°çš„æ˜¯ä»€ä¹ˆ]WIT-1.7.10-1.0.8-1.jar) UCHIJAAAA	levels{r3.0.1} [Levels] ([ç­‰çº§ç³»ç»Ÿ]Levels-1.7.10-r3.0.1-CN.jar) UCHIJAAAA	betterstorage{0.13.1.131-TFC} [BetterStorage] (BetterStorage-1.7.10-0.13.1.131-TFC.jar) UCHIJAAAA BiblioWoodsTFC{1.2} [BiblioWoodsTFC] (BiblioWoods[TerraFirmaCraftV0.79.23][v1.2].jar) UCHIJAAAA	cookingwithtfc{0.0.5.0} [Cooking with TFC] (CookingWithTFC-1.7.10-0.0.5.0.jar) UCHIJAAAA	farseek{1.0.11} [Farseek] (Farseek-1.0.11.jar) UCHIJAAAA is_mtc{1.7.8} [Mine Trading Cards] (Mine Trading Cards-1.7.8.jar) UCHIJAAAA	MineTweaker3{3.0.10} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.10B.jar) UCHIJAAAA	streams{0.2} [Streams] (Streams-0.2.jar) UCHIJAAAA	TerraFirmaCraftNEIplugin{1.5.3.25} [TerraFirmaCraftNEIplugin] (TerraFirmaCraftNEIplugin-1.7.10-1.5.3.25.jar) UCHIJAAAA	tfcrailcraft{0.2.0} [TFC Railcraft Compatibility] (tfcrailcraft-0.2.0.jar) GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread. Profiler Position: N/A (disabled) Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used Player Count: 1 / 8; [EntityPlayerMP['Kijin Seija'/187, l='0999312', x=5966.30, y=138.00, z=-12280.03]] Type: Integrated Server (map_client.txt) Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by StrayWolfe** [comment]
Updating to the latest version(0.79.29.922) of TFC will fix this crash. You are using TFC version 0.79.28.908 which did not have the required methods so it crashed. I will be adding a version checker for TFC to make sure the right version is being used. Thank you for reporting the crash.
