### ISSUE TITLE
Walnut logs won't fill log piles

### ISSUE THREAD

**Issue by Minitiate** [StrayWolfe/Cooking-with-TFC#7]
Found a small bug while playing with the latest release (Going Nuts) - when trying to put walnut logs in log piles, they only fill up the top left spot, and can't be placed or shift-clicked into any of the other three slots.
![will not](https://cloud.githubusercontent.com/assets/26644175/24283153/7f5e3ffa-103a-11e7-90f1-dd9aa9c5deae.png)
Enjoying the rest of the mod so far, though - great work!

**Comment by Minitiate** [comment]
Actually, the problem is a little different from what I described.

Shift + right clicking with a walnut log on the ground forms a log pile as normal.  To add logs to a pile, one has to hold shift and right click with logs on the pile (you can't just right-click without shift like you can in vanilla).  This will fill all possible slots, and walnut logs can go into piles started by walnut and non-walnut logs.  When using the woodpile GUI is where the major problems are - you can't put a walnut log into an empty slot or place walnut logs on top of other walnut logs; all you can do is shift-click walnut logs into slots that already contain walnut logs.

Hope this is helpful!

**Comment by StrayWolfe** [comment]
Thanks for the report. I actually knew of this issue before I even made the log as it is a problem with the way TFC log piles accept logs and unless it is a TFC log it doesn't accept it the same way. Unfortunately there isn't much I can do.
